name: Integrating features changes to dev branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  unit_and_integration_step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Run backend unit tests
        run: |
          pytest
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
      - name: Run frontend end-to-end tests
        working-directory: frontend
        run: |
          npm run build
          npx playwright install --with-deps
          npx playwright test

  build_docker_image:
    needs: unit_and_integration_step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the app
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          docker compose -f ./deploy/docker-compose.staging.yml build --no-cache
  
  promote_to_dev:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install ML deps
        run: |
          pip install -r ./requirements.txt 
      - name: give alias dev 
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MODEL_NAME: weather-model
          MODEL_ALIAS: dev
          NEW_MODEL_ALIAS: dev
        run: |
          python training/assign_tag.py
  